version: "3.8"

services:
  app:
    image: mcr.microsoft.com/devcontainers/base:bullseye
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    networks:
      - backstage-myself

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - 5435:5432
    networks:
      - backstage-myself

networks:
  backstage-myself: